# -*- coding: utf-8 -*-
"""is_anagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5pGTNis2okJrNpXdGssKI-cEcl90IxW
"""

s1 = 'cat'
s2 = 'rat'

def is_anagram(str_1, str_2):

  if len(str_1) == len(str_2):
    sorted_str_1 = sorted(str_1)
    sorted_str_2 = sorted(str_2)

    if sorted_str_1 == sorted_str_2:
      return True
    else:
      return False
  else:
    return False

is_anagram(s1, s2)

