# -*- coding: utf-8 -*-
"""reading_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1371O1HkC2yP4V6DlZgC80iLvDT52d62F
"""

# df = read('file.csv')
# df.write('file_.csv)
# df1 = read('file_new.csv')
# df.compare(df1)

import pandas as pd

mtcars = pd.read_csv('mtcars.csv')

mtcars

mtcars.to_csv('mtcarsNew.csv', index = False)

mtcarsnew = pd.read_csv('mtcarsNew.csv')

mtcarsnew.compare(mtcars)

NHL = pd.read_excel('NHL 2015-16.xlsx')

NHL

NHL.to_excel('NHLNew.xlsx')

beer = pd.read_fwf('beer.txt')

beer

beer.to_csv('beerNew.txt', index = False)

beerNew = pd.read_fwf('beerNew.txt')

beerNew.compare(beer)

data = pd.read_csv('u.data')

data

data.to_csv('u.dataNew', index = False)

dataNew = pd.read_csv('u.dataNew')

dataNew.compare(data)

item = pd.read_csv('u.item', sep = '\t', encoding='latin-1')

item

item.to_csv('u.itemNew', index = False)

itemNew = pd.read_csv('u.itemNew', sep = '\t', encoding='latin-1')

itemNew.compare(item)

def read_file(file):
  if file.endswith('csv'):
    return pd.read_csv(file)
  elif file.endswith('xlsx'):
    return pd.read_excel(file)
  elif file.endswith('txt'):
    return pd.read_fwf(file)
  else:
    return pd.read_csv(file, sep = '\t', encoding='latin-1')

read_file('beer.txt')

