# -*- coding: utf-8 -*-
"""reading_json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BoqfZEbjefIi-A7PQKUIAz4U20CCFp5A
"""

import pandas as pd
import json

with open('/content/json_file.txt', 'r') as f:
  json_obj = json.load(f)

for item in json_obj:
        for key, value in item.items():
            print(key, ':', value)
        print('==================')

with open('/content/daily_covid_cases.json', 'r') as f:

  covid_obj = json.load(f)

  print('meta')
  for key, value in covid_obj['meta'].items():
      print(key, ':', value,)

  print('\n')

  print('data')
  for key, value in covid_obj['data'].items():
    print(key, ':', value)

