# -*- coding: utf-8 -*-
"""stroke_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bFccLhcml48t7B-XKAfwtd4zhtXp70l-
"""

import pandas as pd

stroke_data = pd.read_csv('/content/healthcare-dataset-stroke-data.csv')
stroke_data

stroke_data.describe()

stroke_data.select_dtypes(include=float).describe()

stroke_data.groupby('stroke')

stroke1 = stroke_data.groupby("stroke").get_group(1,)

stroke1_describe = stroke1.describe()
stroke1_describe

stroke1_int = stroke1.select_dtypes(include=int)
stroke1_int

stroke1_int.describe()

heart_hype = stroke_data.groupby(['hypertension', 'heart_disease'])

heart_hype1 = stroke_data.groupby(['hypertension', 'heart_disease']).get_group((1,1))

heart_hype['id'].agg('count')

heart_hype['stroke'].mean()

heart_hype['stroke'].std()

