# -*- coding: utf-8 -*-
"""birthday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHajxxLhGLG4tDXGaFl3TtJTZ8QnbJZr
"""

import datetime as dt

birthday = dt.date(1979, 8, 22)

def age (bday):
  age_today = (dt.date.today() - bday).days


  years = str((age_today)/365)
  unit = 'years old'
  print(years + ' years old')

age(birthday)

