# -*- coding: utf-8 -*-
"""thanksgiving.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lM6TUePvMqx3cg3dfX78hP5sBknn9N6d
"""

import datetime as dt

today = dt.date.today()
thanksgiving = dt.date(2024, 11, 28)

count_down = thanksgiving - today
count_down

