# -*- coding: utf-8 -*-
"""python_lists_and_tuples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-1mLjZ6MW4jF8l7Vi3qSx7vaFije-Wx
"""

L1 = 'abcdefghijklmnopqrstuvwxyz'

def lists(x):
  L2 = []

  for index in range(len(x)):
    L2.append(index +1)

  return list(zip(L2, x))

print(lists(L1))

