# -*- coding: utf-8 -*-
"""bracket_matcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqM1phrnyxdSyaxWH8FkAo7dwzzqVOMi
"""

l = '(a((klmns)t))uvwz)'

def BracketMatcher(s):
  countOpen = 0
  countClose = 0
  open = ''
  close = ''

  for i in range(len(s)):
    if s[i] == '(':
      countOpen = countOpen + 1
    elif s[i] == ')':
      countClose = countClose +1
    else:
       pass
  if countOpen == countClose:
    return True
  else:
    return False

BracketMatcher(l)

