# -*- coding: utf-8 -*-
"""scraping_formula1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13VN6R7nLhsqP0qJwdItVKEq5_vaeLSd5
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

url = 'https://www.formula1.com/en/results.html/2022/drivers.html'

r = requests.get(url)

r.status_code

soup = BeautifulSoup(r.content)

tables = soup.find_all('table')

len(tables)

data_table = tables[0]

header_data = data_table.find_all('th')

header_data

headers = []
for h in header_data:
  name = h.get_text()
  headers.append(name)

headers

row_data = data_table.find_all('tr')

rows = []

for tr in row_data[1:]:
  tds = tr.find_all('td')
  row = [td.get_text() for td in tds]
  rows.append(row)

df = pd.DataFrame(rows, columns = headers)
df

df.to_csv('formula_1.csv', index = False)

pd.read_csv('formula_1.csv')

df_pd = pd.read_html(url)[0]
df_pd

