# -*- coding: utf-8 -*-
"""merge_join_telecom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMwKgVEH7muiIFT2smMWgG-ZjfX_g1uJ
"""

import pandas as pd

event = pd.read_csv('event_type.csv')
log = pd.read_csv('log_feature.csv')
resource = pd.read_csv('resource_type.csv')
severity = pd.read_csv('severity_type.csv')
train = pd.read_csv('train.csv')

event

log

event_log_outer = event.merge(log, how='outer')
event_log_outer

event_log_outer

resource_severity_outer = resource.merge(severity, how='outer')

event_log_train_outer = event_log_outer.merge(train, how='outer')

total_outer = event_log_train_outer.merge(resource_severity_outer, how='outer')

total_outer

"""**2. Explain the difference between inner and outer merge:**


 An inner merge only grabs the shared values from each dataframe. And outer merge grabs all values from both dataframes

**3. Explain the difference between merge and join:**

Join combines dataframes based on their indicies. Merge allows you to specify additional columns to be merged.
"""

total_outer1 = total_outer[:73211]
total_outer2 = total_outer[73211:]

pd.concat([total_outer1, total_outer2], axis = 0)

total_outer.drop_duplicates()

